SET(QPID_PROTON_FOUND "NO")

set(prg86 "PROGRAMFILES(X86)")

SET(QPID_PROTON_SEARCH_PATHS
	$ENV{ProgramFiles}/Proton/
	$ENV{${prg86}}/Proton/
	/usr/local/
    /sw/
	/usr/
)

FIND_PATH(QPID_PROTON_INCLUDE_DIR
	NAMES proton/messenger.h
	PATH_SUFFIXES /include/
	PATHS ${QPID_PROTON_SEARCH_PATHS}
)

IF (WIN32)
	FIND_LIBRARY(QPID_PROTON_LIBRARY
		NAMES qpid-proton qpid-protond
		PATH_SUFFIXES /lib/ /Release/ /Debug/
		PATHS ${QPID_PROTON_SEARCH_PATHS}
	)
ELSE()
	FIND_LIBRARY(QPID_PROTON_LIBRARY
		NAMES qpid-proton
		PATH_SUFFIXES /lib/ /lib64/
		PATHS ${QPID_PROTON_SEARCH_PATHS}
	)
ENDIF()

MESSAGE("${QPID_PROTON_LIBRARY}")

IF(QPID_PROTON_LIBRARY AND QPID_PROTON_INCLUDE_DIR)
  SET(QPID_PROTON_FOUND "YES")
ENDIF(QPID_PROTON_LIBRARY AND QPID_PROTON_INCLUDE_DIR)

IF(QPID_PROTON_LIBRARY)
	SET(CMAKE_REQUIRED_LIBRARIES ${QPID_PROTON_LIBRARY})
ENDIF(QPID_PROTON_LIBRARY)

IF(QPID_PROTON_FOUND)
  IF(NOT QPID_PROTON_FIND_QUIETLY)
    MESSAGE(STATUS "Found QPID_PROTON: ${QPID_PROTON_LIBRARY},${QPID_PROTON_INCLUDE_DIR}")
  ENDIF(NOT QPID_PROTON_FIND_QUIETLY)
ELSE(QPID_PROTON_FOUND)
  IF(QPID_PROTON_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find QPID_PROTON Library")
  ENDIF(QPID_PROTON_FIND_REQUIRED)
ENDIF(QPID_PROTON_FOUND)